<?php
return array (
  1 => 
  array (
    'id' => '1',
    'catid' => '10',
    'typeid' => '57',
    'title' => '公司动态测试1',
    'style' => '',
    'thumb' => '',
    'keywords' => '动态 公司',
    'description' => '世界上的就是打开',
    'posids' => '0',
    'url' => 'http://yangshi.localhost.com/index.php?m=content&c=index&a=show&catid=10&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1510821582',
    'updatetime' => '1510821606',
    'hitsid' => 'c-1-1',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  2 => 
  array (
    'id' => '2',
    'catid' => '10',
    'typeid' => '57',
    'title' => '公司动态新闻测试2',
    'style' => '',
    'thumb' => '',
    'keywords' => '动态 公司 新闻',
    'description' => '说的就是的就是打开',
    'posids' => '0',
    'url' => 'http://yangshi.localhost.com/index.php?m=content&c=index&a=show&catid=10&id=2',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1510821608',
    'updatetime' => '1510821625',
    'hitsid' => 'c-1-2',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>